---
-
  gather_facts: false
  hosts: ec2-server
  remote_user: ec2-user
  tasks:
    -
      name: “Wait for SSH to come up”
      wait_for_connection:
        delay: 5
        timeout: 90
    -
      ec2_metadata_facts: ~
      name: “Collect instance facts”
    -
      become: true
      name: “Install Apache2”
      apt:
        name: apache2
        state: present
    -
      become: true
      name: “Start Apache2"
      service:
        enabled: true
        name: apache2
        state: started
    -
      become: true
      name: “Deploy content”
      template:
        dest: /var/www/html/index.html
        src: ./index.html
