---
- hosts: CentOS
  become: yes
  become_method: sudo
  vars_files:
   - vars/var_file.yml
  tasks:
    #Install Apache Server # Install the apache httpd
  - name: Install Apache HTTP
    yum:
     name: httpd
     state: present
  - name: Run Apache HTTP
    service: # Ensure httpd is running
     name: httpd
     state: started
    #shell: firewall-cmd --permanent --add-service=http && firewall-cmd --reload #Opening firewall for HTTP && reloading it.
  - name: Open port 8080 for http access
    firewalld:
     port: "{{apache_listen_port}}/tcp"
     zone: public
     permanent: true
     state: enabled
     immediate: true

  - name: Load the firewall changes in firewalld service
    service:
     name: firewalld
     state: restarted

  - name: Copy HTML file
    copy:
      src: files/index.html
      dest: /var/www/html/index.html
  - name: Stop Apache HTTP Server
    yum:
      name: httpd
      state: absent
      autoremove: yes
    tags:
      - stop-apache
